Setup and Mobile First
sahlminkok/Portfolio pull request #1
Opened 2023-03-28 11:12 UTC by sahlminkok

## Setup and Mobile First
### In this project we:
1. Add Linter files
2. Add HTML and CSS for mobile_first

2023-03-28 11:34 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @sahlminkok, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 11:34 UTC, Qoosim commented on index.html
> +  </nav>
- [ ] It is required that this header should have a container section called `header` tag. The header tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation. You can check this [article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info.
The expected structure should be like below.

```
 <header class="navigation">
    <a href="#">
      <img src="images/cabsal.png" id="logo" alt="my logo">
    </a>
    <nav>
      <a href="#">
        <img src="images/Icon - Menu.png" id="menu" alt="Menu"> 
      </a>
    </nav> 
  </header>
```

2023-03-28 11:34 UTC, Qoosim commented on index.html
> +  <section class="Header">
- [OPTIONAL] I would recommend you to change the class name to something else for consistency sake. something like `headline-section` could be a better optional.

2023-03-28 13:23 UTC, sahlminkok commented
@Qoosim I have fixed the issues.

2023-03-28 15:40 UTC, levy002 approved these changes
## Hello @sahlminkok 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 15:49 UTC, merged

2023-04-27 16:48 UTC, Zuhaib042 reviewed
Hi @sahlminkok 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a pull request for another project. kindly submit the PR for the  HTML + basic JavaScript Capstone project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._